### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by billiboy** [typesense/typesense-go#104]
## Description
I am trying the examples as reported in the golang api document but I get this error when I create an index:
https://i.imgur.com/t6gQa0m.png

**Comment by v-byte-cpu** [comment]
Hi @billiboy, you need to replace the `true` literal with a pointer to bool. We will update readme to reflect the changes in api.

**Comment by billiboy** [comment]
> Hi @billiboy, you need to replace the `true` literal with a pointer to bool. We will update readme to reflect the changes in api.

give me an example of how I should do? I'm not very practical, I'm still learning go

**Comment by billiboy** [comment]
> Hi @billiboy, you need to replace the `true` literal with a pointer to bool. We will update readme to reflect the changes in api.
is it okay to do it this way?

func BoolPointer(b bool) *bool {
	return &b
}
