### ISSUE TITLE
`api.ApiKeySchema` is missing the optional `Value` field for create API keys

### ISSUE THREAD

**Issue by dbolkensteyn** [typesense/typesense-go#110]
The documentation https://typesense.org/docs/0.23.1/api/api-keys.html#create-an-api-key states that a value can optionally passed when creating an API key, which will be used instead of generating a new random one.

`ApiKeySchema` is thus missing a `Value` field: https://github.com/typesense/typesense-go/blob/master/typesense/api/types_gen.go#L33

Typesense version 0.23.1

Thank you for providing this awesome Go client 🙇

**Comment by kishorenc** [comment]
Need to update the [Open API spec](https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml) and then once it's merged,  need to regenerate the go types with `go generate` (which fetches the spec and does some go-specific tuning and then generates the types). 

Happy to accept PRs, or I will have to get around to this when time permits.

**Comment by kishorenc** [comment]
Fixed in `v0.6.0`.
