### ISSUE TITLE
wrong type on an attribute in the *SearchCollectionParams struct

### ISSUE THREAD

**Issue by WahidinAji** [typesense/typesense-go#123]
## Description

I try to search the collection by param. but got an error

## Steps to reproduce

I follow this instruction, but I think there is an error type on the `SearchCollectionParams struct` 
![image](https://user-images.githubusercontent.com/48281037/200114449-30ecf1ea-d2a2-403f-97e2-bc701de7ae8e.png)

on the sample, the `QueryBy` uses a string-array, such as 
```go
QueryBy []string
```

but, when I go to the struct, the type is just string not array-string
```go
QueryBy string
```
![image](https://user-images.githubusercontent.com/48281037/200114589-9d053081-9868-4fe4-8d7a-dd1e4291cf98.png)

So, in that case. I must uses only string like
```go
QueryBy: "field"
```
and can't uses array-string
```go
QueryBy: []string{"field_1", "field_2"}
```

**Typsense Version**:
```json
{
    "state": 1,
    "version": "0.24.0.rcn13"
}
```

**OS**:  Ubuntu 22.04.1 LTS x86_64

**Comment by kishorenc** [comment]
Fixed by https://github.com/typesense/typesense-go/pull/122
