### ISSUE TITLE
Generated api is missing values as compared to typesense-js

### ISSUE THREAD

**Issue by yckbilly1929** [typesense/typesense-go#126]
## Description

SearchHighlight is missing 'value'
https://github.com/typesense/typesense-go/blob/1bbb388b6a50ac9225f2b980b78610dfc4d53469/typesense/api/generator/openapi.yml#L1398

which exisits in typesense-js version
https://github.com/typesense/typesense-js/blob/50c834c103c502e21dc892827077d503015e9767/src/Typesense/Documents.ts#L77

and needed for transformItems in vue-instantsearch
https://github.com/algolia/vue-instantsearch/blob/751ffda63ef32328429d5b73ec46dc443e771605/src/util/parseAlgoliaHit.js#L96
https://github.com/algolia/instantsearch.js/blob/644f456e7ec43be0851c5a5d6ab194710ab51647/packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts#L333

## Expected Behavior

typesense-go client should work in the same way as typesense-js

## Actual Behavior

missing 'value' from typesense-go makes it impossible to custom render 

## Metadata

**Typesense Version**: 0.23.1

**OS**: Ubuntu 22.04

**Comment by kishorenc** [comment]
Fixed.
