### ISSUE TITLE
Is there a way to check the type of error?

### ISSUE THREAD

**Issue by Yothgewalt** [typesense/typesense-go#146]
## Description

I don't know how to check the error type, for example, is it 404 or 409 etc.

Now I replace it by using the split function to grab the httpcode and check it.

And I'd like to ask, is there a better way?

## Metadata

**Typesense Version**:

**OS**:

**Comment by vamshiaruru** [comment]
```go
	target := &typesense.HTTPError{} // nolint:exhaustruct
	if errors.As(err, &target) {
		t := *target
		fmt.Println(t.Status, t.Body)
	}

```

**Comment by Yothgewalt** [comment]
> ```go
> 	target := &typesense.HTTPError{} // nolint:exhaustruct
> 	if errors.As(err, &target) {
> 		t := *target
> 		fmt.Println(t.Status, t.Body)
> 	}
> ```

Thank you, Its working!
