### ISSUE TITLE
QueryBy is "" if it's not set

### ISSUE THREAD

**Issue by leapoly** [typesense/typesense-go#173]
## Description

If I omit the field `QueryBy` doing a search in a single collection (because I'm using a preset), `NewSearchCollectionRequest` generates an empty `query_by` and it's wrong. This field should be omitted in the query.

Example:

"https://.....typesense.net:443/collections/Name/documents/search?include_fields=id&page=1&per_page=100&preset=Preset&q=test&query_by="

## Steps to reproduce

Don't include `QueryBy`
![image](https://github.com/user-attachments/assets/384f010d-e7b5-451c-8771-84f83ba8e841)

## Expected Behavior

Don't add `query_by=` in the GET.

If I use the MultiSearch, it works
![image](https://github.com/user-attachments/assets/ad3bd6aa-9213-413e-853a-05d0d393a569)

## Actual Behavior

It adds `query_by=` in the GET

## Metadata

**Typesense Version**:  typesense-go v1.1.0

**OS**: Mac

**Comment by phiHero** [comment]
Fixed in https://github.com/typesense/typesense-go/pull/174
