### ISSUE TITLE
Facets fail on json unmarshal

### ISSUE THREAD

**Issue by agentabstract** [typesense/typesense-go#69]
## Description

While doing my initial testing, I setup a field to facet by and when I tried to to search with that facet on I got a json unmarshal error.

## Steps to reproduce

1) created schema with: {Name:  "type", Type:  "string", Facet: true}
2) indexed documents that were all the same type.
3) did a search with the option FacetBy: &[]string{"type"}

## Expected Behavior

A count of results of that type.

## Actual Behavior
ERROR: json: cannot unmarshal object into Go struct field SearchResult.facet_counts of type int

**Comment by v-byte-cpu** [comment]
Hi @agentabstract :clap: ! I will take a look at it soon

**Comment by hm-you** [comment]
I have same issue here

**Comment by razorness** [comment]
linking this to https://github.com/typesense/typesense-api-spec/issues/20
