### ISSUE TITLE
URL encoding of params

### ISSUE THREAD

**Issue by kishorenc** [typesense/typesense-go#71]
## Description

The `FilterBy` parameter can contain special characters which must be encoded by the client before making the HTTP request. Context: https://github.com/typesense/typesense/issues/210#issuecomment-863724449

## Steps to reproduce

Making a query like this:

```
FilterBy: pointer.String("num_employees:>=100 && num_employees:<=300")
```

## Expected Behavior

Typesense should received the following URL encoded `filter_by` value:

```
num_employees%3A%3E%3D100%20%26%26%20num_employees%3A%3C%3D300
```

## Actual Behavior

Typesense receives the following incorrect query param value:

```
num_employees%3A%3E%3D100
```

## Metadata

**Typsense Version**: All

**OS**: All

**Comment by kishorenc** [comment]
@v-byte-cpu Would appreciate your 👀 on this issue.

**Comment by v-byte-cpu** [comment]
I will look at this issue in the next few days
