### ISSUE TITLE
930 go.sum imports?

### ISSUE THREAD

**Issue by lacroixsteven** [typesense/typesense-go#74]
## Description

Anyway the go.sum can be cleaned up? Having 930 imports seems pretty insane. Any reason for this? Thanks!

**Comment by v-byte-cpu** [comment]
We don't control `go.sum` file, it is updated automatically using `go get` command and maintained with `go mod tidy`.

**Comment by lacroixsteven** [comment]
Oh true, that makes sense. Thanks for the reply @v-byte-cpu
