### ISSUE TITLE
FilterBy conditions after the first are ignored

### ISSUE THREAD

**Issue by HendrikGrobler** [typesense/typesense-go#81]
## Description

When querying using a FilterBy string with multiple conditions separated by &&, only the first condition is applied, the rest seem to be ignored. This seems to be related to encoding/escaping. After digging around in the source code for a bit I managed to work around this issue by URL encoding the "&&" characters as (%26%26) when building the FilterBy string.

Create a FilterBy string with multiple conditions separated by &&

## Expected Behavior

All conditions should be applied

Conditions after the first are ignored

**Typsense Version**: typesense-server-0.21.0-linux-amd64

**OS**: Linux Mint

**Comment by kishorenc** [comment]
@HendrikGrobler 

This was fixed recently [here](https://github.com/typesense/typesense-go/pull/77) -- can you try with the HEAD?
