### ISSUE TITLE
export collection causes response_abort

### ISSUE THREAD

**Issue by minarc** [typesense/typesense-go#87]
``` go
read, err := ts.Collection("test").Documents().Export()
if err != nil {
    panic(err.Error())
}
```

It returns no err but io.Reader has 0 bytes.
If we call export function then typesense log "response abort called"

<img width="726" alt="image" src="https://user-images.githubusercontent.com/11865340/142789102-17847944-3670-47f3-9574-8bbbb73bd9d4.png">

**Comment by harisarang** [comment]
Hey @minarc What version of typesense-go you are using ?
Is it the [HEAD](https://github.com/typesense/typesense-go/commit/0ec950e12939426f4413ffc04793afb29526be0d) at master ?

**Comment by minarc** [comment]
@harisarang Typesense is 0.22.0 and go client is v0.3.0.

**Comment by minarc** [comment]
@harisarang I just tried ```go get github.com/typesense/typesense-go@master``` but  I found that master branch missing TextMatch field at SearchResultHit also.

**Comment by harisarang** [comment]
> @harisarang I just tried `go get github.com/typesense/typesense-go@master` but I found that master branch missing TextMatch field at SearchResultHit also.

@minarc 
Hey thanks, for pointing that out ! Now, check master it is fixed !

**Comment by harisarang** [comment]
> ```go
> read, err := ts.Collection("test").Documents().Export()
> if err != nil {
>     panic(err.Error())
> }
> ```
> 
> It returns no err but io.Reader has 0 bytes. If we call export function then typesense log "response abort called"
> 
> <img alt="image" width="726" src="https://user-images.githubusercontent.com/11865340/142789102-17847944-3670-47f3-9574-8bbbb73bd9d4.png">

@minarc 
Will look into this in couple of days

**Comment by minarc** [comment]
@harisarang Thank you for your great and quick works! 👍🏻

**Comment by hm-you** [comment]
@harisarang Any updates?

**Comment by harisarang** [comment]
Hey @minarc!
I was looking into this issue, for me, Export works as expected !
Maybe try updating your typesense-server version to `v0.22.1`.

P.S. If you facing the same issue again can you share with me a small reproduceble dataset with a example code snippet so that I can investigate on it !
